### ISSUE TITLE
Error on connection

### ISSUE THREAD

**Issue by anasoid** [darrensmithwtc/jmeter-backend-newrelic#1]
Jmeter 5.4.1 , OpenJDK 11, OS : ubuntu

I have this error
2021-10-26 11:11:21,646 INFO o.a.j.v.b.BackendListener: Backend Listener: Starting worker with class: class io.github.darrensmithwtc.jmeter.backendlistener.newrelic.NewRelicBackendClient and queue capacity: 5000
2021-10-26 11:11:21,647 INFO o.a.j.v.b.BackendListener: Backend Listener: Started  worker with class: class io.github.darrensmithwtc.jmeter.backendlistener.newrelic.NewRelicBackendClient
2021-10-26 11:11:21,659 ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,6,main]
java.lang.NoSuchMethodError: 'okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.callTimeout(java.time.Duration)'
	at com.newrelic.telemetry.OkHttpPoster.<init>(OkHttpPoster.java:34) ~[jmeter.backendlistener.newrelic-0.0.4-20210922.172740-1.jar:?]
	at com.newrelic.telemetry.OkHttpPoster.<init>(OkHttpPoster.java:25) ~[jmeter.backendlistener.newrelic-0.0.4-20210922.172740-1.jar:?]
	at com.newrelic.telemetry.MetricBatchSenderFactory.configureWith(MetricBatchSenderFactory.java:59) ~[jmeter.backendlistener.newrelic-0.0.4-20210922.172740-1.jar:?]
	at io.github.darrensmithwtc.jmeter.backendlistener.newrelic.NewRelicBackendClient.setupTest(NewRelicBackendClient.java:173) ~[jmeter.backendlistener.newrelic-0.0.4-20210922.172740-1.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:325) ~[ApacheJMeter_components.jar:5.4.1]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:280) ~[ApacheJMeter_components.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:205) ~[ApacheJMeter_core.jar:5.4.1]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:382) ~[ApacheJMeter_core.jar:5.4.1]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by GKAccessGroup** [comment]
Hey @anasoid 

I am facing same issue, were you able to resolve it?

Thanks.

**Comment by anasoid** [comment]
Hello @GKAccessGroup ,

Unfortunately no :(

Best regards

**Comment by BalakrishnaLTI** [comment]
Hi @anasoid @GKAccessGroup @darrensmithwtc 

I am also facing same issue, were you able to resolve it?

ERROR o.a.j.JMeter: Uncaught exception in thread Thread[StandardJMeterEngine,5,main]
java.lang.NoSuchMethodError: 'okhttp3.OkHttpClient$Builder okhttp3.OkHttpClient$Builder.callTimeout(java.time.Duration)'
	at com.newrelic.telemetry.OkHttpPoster.<init>(OkHttpPoster.java:34) ~[jmeter.backendlistener.newrelic-0.0.4-SNAPSHOT.jar:?]
	at com.newrelic.telemetry.OkHttpPoster.<init>(OkHttpPoster.java:25) ~[jmeter.backendlistener.newrelic-0.0.4-SNAPSHOT.jar:?]
	at com.newrelic.telemetry.MetricBatchSenderFactory.configureWith(MetricBatchSenderFactory.java:59) ~[jmeter.backendlistener.newrelic-0.0.4-SNAPSHOT.jar:?]
	at io.github.darrensmithwtc.jmeter.backendlistener.newrelic.NewRelicBackendClient.setupTest(NewRelicBackendClient.java:173) ~[jmeter.backendlistener.newrelic-0.0.4-SNAPSHOT.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:325) ~[ApacheJMeter_components.jar:5.3]
	at org.apache.jmeter.visualizers.backend.BackendListener.testStarted(BackendListener.java:280) ~[ApacheJMeter_components.jar:5.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfStart(StandardJMeterEngine.java:205) ~[ApacheJMeter_core.jar:5.3]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:380) ~[ApacheJMeter_core.jar:5.3]
	at java.lang.Thread.run(Thread.java:829) [?:?]

**Comment by darrensmithwtc** [comment]
Hey folks,

Sorry - missed the comments last year, this was for a project we needed at the time and haven't revisited it since.

I'm guessing the timeout is related to connectivity from the injector to the New Relic endpoint.

Quick Questions:

* Is your New Relic account in Europe?
  * Have you set a connectionString property ? 
  * The code  defaults to the EU endpoint otherwise https://metric-api.eu.newrelic.com/metric/v1

* Can you get to that endpoint from the load injector?
  * It you do a GET request it should return " {} "

**Comment by BalakrishnaLTI** [comment]
@darrensmithwtc 
Thanks for the reply.

We are able to integrate Jmeter results with Newrelic when executing the test locally from Windows machine.

But, We are getting the above issues only when we are executing the test from cloud in Linux Ubuntu machine.

Using the below connection string in Jmeter Backend Listener.
https://metric-api.newrelic.com/metric/v1

Could you please help on this issue.
